version: '3.8'
services:
  webserver:
    image: nginx:latest
    ports:
    - 8888:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: fluentd
      options:
        tag: honeypot.webserver
    depends_on:
      logging:
        condition: service_healthy
  database:
    image: wildwildangel/mysql-honeypotd
    environment:
    - MYSQL_ROOT_PASSWORD=5547
    volumes:
    - db_data:/var/lib/mysql
    logging:
      driver: fluentd
      options:
        tag: honeypot.database
    depends_on:
      logging:
        condition: service_healthy
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.honeypot
    ports:
    - 5000:5000
    logging:
      driver: fluentd
      options:
        tag: honeypot.api
    depends_on:
      logging:
        condition: service_healthy
  logging:
    image: fluent/fluentd:v1.16-1
    ports:
    - 24224:24224
    - 24224:24224/udp
    volumes:
    - ./fluentd/conf:/fluentd/etc
    restart: always
    healthcheck:
      test:
      - CMD-SHELL
      - nc -z 127.0.0.1 24224
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  db_data: null
x-metadata:
  blueprint_version: '1.0'
  generated_at: '2025-08-11T03:03:49.435345+09:00'
  generator: HoneypotBlueprintGenerator
