# docker-compose.yml
version: '3.8'
services:
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=5547
    volumes:
      - db_data:/var/lib/mysql
  api:
    build: ./api
    ports:
      - "5000:5000"

volumes:
  db_data:

# This is a test